/**
 * Author : Faruq
 * List Constant
 */

module.exports = {
    DEVICE_ACTIVE:1,
    DEVICE_NONACTIVE:0,
    DEVICE_PENDING:2,
    NORMAL_CONDITION:1,
    ABNORMAL_CONDITION:0,
    HEARTRATE_LOWER_LIMIT:48,
    HEARTRATE_UPPER_LIMIT:80,
    TEMPERATURE_LOWER_LIMIT:37,
    TEMPERATURE_UPPER_LIMIT:39,

  }